# environment.yaml
name: marketing-research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - google-genai==0.2.2
    - langchain==0.3.13
    - langchain-chroma==0.1.4
    - langchain-huggingface==0.1.2
    - langchain-text-splitters==0.3.5
    - chromadb==0.5.23
    - sentence-transformers==3.3.1
    - pyyaml==6.0.2
    - colorama==0.4.6
    - python-dotenv==1.0.1
    - onnxruntime==1.15.1